### ISSUE TITLE
how to get this to run in obsidian

### ISSUE THREAD

**Issue by ReinerD** [qijie44/obsidian-SMILESRender-plugin#1]
Hello, since release 1.0 is pretty recent, I figure it's actually functional. In my hands, however, I couldn't get it to run, so far. Maybe you can help me.
Here's what I did:
In the obsidian instance, install Obsidian42-BRAT
there, add qijie44/obsidian-SMILESRender-plugin
and activate it in community-plugins:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/10863233/229752024-e2e8a951-415f-4aa5-82bf-88077653cc84.png">
But: 
<img width="777" alt="image" src="https://user-images.githubusercontent.com/10863233/229752392-89f5a7f0-609a-4634-b7cb-1379c61687f5.png">
renders as
<img width="732" alt="image" src="https://user-images.githubusercontent.com/10863233/229752482-5989e4bb-524a-4670-826d-8530baaa321f.png">

Did I miss a point ?

**Comment by qijie44** [comment]
Hi, i seemed to have uploaded the wrong file, I have patched it now, try using the latest release.

**Comment by ReinerD** [comment]
Does still not work here:

* disabled and uninstalled the old version
* added new plug inversion:

* enabled it : It’s still showing version 1.0.0 ! Maybe you didn’t update this in the manifest ?

* no change in behaviour:

Let me know if I can help somehow.

**Comment by qijie44** [comment]
Hi Reiner, you could try forcing BART to use 1.0.1 release. I have no idea why it doesn't use it, but you can run the command Plugins: Add a beta plugin with frozen version based on a release tag, put in the link and use 1.0.1 as the version.

![image](https://user-images.githubusercontent.com/45685206/229825131-0d28ce4d-38d6-4a54-bc9d-d92a6fcf6601.png)
![image](https://user-images.githubusercontent.com/45685206/229825266-cd9690a8-82cc-40d1-8fa4-1434428cb80b.png)

**Comment by ReinerD** [comment]
Hu qijie44,

well, that’s what I did. To me it looks as if the version info is still 1.0.0 n the manifest.json. Is there another way of seeing which version is loaded ?

**Comment by qijie44** [comment]
Hi Reiner, 

Could you try this again just in case? The main.js file should be 3,863kb from the file explorer and 3.77kb as the size on disk

> Hi Reiner, you could try forcing BART to use 1.0.1 release. I have no idea why it doesn't use it, but you can run the command Plugins: Add a beta plugin with frozen version based on a release tag, put in the link and use 1.0.1 as the version.
> 
> ![image](https://user-images.githubusercontent.com/45685206/229825131-0d28ce4d-38d6-4a54-bc9d-d92a6fcf6601.png) ![image](https://user-images.githubusercontent.com/45685206/229825266-cd9690a8-82cc-40d1-8fa4-1434428cb80b.png)

**Comment by qijie44** [comment]
If it still doesn't work, you could send me your copy of the plugin, as I can't replicate the error on my end

**Comment by ReinerD** [comment]
When installing it via the main addin box:
<img width="642" alt="image" src="https://user-images.githubusercontent.com/10863233/229847047-9faf7992-a5bf-4b92-bc7a-6d679ec05c85.png">


via frozen version 1.0.0
<img width="644" alt="image" src="https://user-images.githubusercontent.com/10863233/229847099-92c024fd-dba7-4e7c-8972-99a3d53bf28a.png">

and for frozen version 1.0.1
<img width="271" alt="image" src="https://user-images.githubusercontent.com/10863233/229847149-3e3be5ea-0200-44ba-99e6-77aac7513d00.png">
<img width="642" alt="image" src="https://user-images.githubusercontent.com/10863233/229847197-eac9549d-3cad-472e-a83a-0e57d680e14e.png">
<img width="808" alt="image" src="https://user-images.githubusercontent.com/10863233/229847265-a4959208-8ef4-44ee-aaf5-122e27b63091.png">


`


Notice that the version has changed.
I attach the stuff in the plugin directory.
[obsidian-chemrender-plugin.zip](https://github.com/qijie44/obsidian-SMILESRender-plugin/files/11150449/obsidian-chemrender-plugin.zip)

Thanks for your help!

**Comment by qijie44** [comment]
Hi Reiner,

Did you switch to reading mode? It doesn't render in editing mode 😅

**Comment by qijie44** [comment]
@ReinerD I discovered another plugin that does the same as this, but better, so I am planning to delete this repo. Here's the link for that plugin, 
https://github.com/Acylation/obsidian-chem
From what I can see, it converts the same way as this plugin, so it should be as simple as deleting this plugin and then installing that plugin. Thanks for trying out this plugin!

**Comment by ReinerD** [comment]
Thanks a lot for pointing that out.  Works.

Il sab 20 gen 2024, 23:09 qijie44 ***@***.***> ha scritto:
